spring:
  application:
    name: service-vedio
    #nacos注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #写自己的nacos端口
## 最大上传单个文件大小：默认1M
## 最大置总上传的数据大小 ：默认10M
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
server:
  port: 8003